### ISSUE TITLE
Dynamic resize 

### ISSUE THREAD

**Issue by deisner** [hrynko/vue-pdf-embed#20]
Thanks for providing this component. I'm coming from [vue-pdf](https://github.com/FranckFreiburger/vue-pdf) and one feature I miss is dynamic resizing. Would it be possible to implement this?

The workaround I've been using for now is to include [vue-resize-sensor](https://github.com/FranckFreiburger/vue-resize-sensor) as a sibling component, and then using the width of the that component to reset the `width` property of the vue-pdf component, which does cause it to re-render. But it would be nice if this feature were built-in.

Thanks!

**Comment by hrynko** [comment]
To be honest, I didn't intend to allow dynamic resizing since `1.1.0`. Because in this version annotation and text layers were introduced, as well as width and height props, which does not allow to have such responsiveness as it was in `1.0.8` and earlier.

However, I see your point and will consider optional dynamic resizing when width and height are not provided.

PS: Thanks for posting your workaround.

PPS: If you don't need annotation and text layers, responsiveness can also be also achieved with plain CSS (by setting the width of the component's canvases to `100%` and the height to `auto`).

**Comment by hrynko** [comment]
Hi @deisner,

I once again considered adding this feature, but I'm still leaning towards using third-party libraries or a style approach. After all, this is a library for embedding PDF documents, while there are well-established solutions for tracking resizing, which in turn are very case-specific. I would like to focus on rendering documents in this library and leave it up to developers to decide what works for them when it comes to dynamic resizing.
