### ISSUE TITLE
Feature request: Download method

### ISSUE THREAD

**Issue by veerman72** [hrynko/vue-pdf-embed#68]
Is there a possibility to create a public method (like the print() method) for direct downloading the rendered pdf. 

````
methods: {
    download () {
      this.$refs.myPdfComponent.download()
    },
}
````

I make use of a source like ``data:application/pdf;base64,<BASE64_ENCODED_PDF>`` to render the pdf.

**Comment by hrynko** [comment]
Hi @veerman72,

Thanks for sharing your idea, I think it might be helpful in some cases. However, it seems to me that this does not quite fit into the concept of the library. It still seems to me that manipulations with this file should be done on the developer's side, since the file is provided by the developer.

**Comment by hrynko** [comment]
Though I can be wrong and you should post your idea in the [discussions](https://github.com/hrynko/vue-pdf-embed/discussions/categories/ideas)

**Comment by veerman72** [comment]
I posted the idea in the discussions section (#71 )
